# System 3.5 GameResource File: [kichiku.inf]
ScenarioA gamedata/鬼畜王sa.ald
GraphicsA gamedata/鬼畜王ga.ald
GraphicsB gamedata/鬼畜王gb.ald
WaveA gamedata/鬼畜王wa.ald
SaveA gamedata/save/鬼畜王sa.asd
SaveB gamedata/save/鬼畜王sb.asd
SaveC gamedata/save/鬼畜王sc.asd
SaveD gamedata/save/鬼畜王sd.asd
SaveE gamedata/save/鬼畜王se.asd
SaveF gamedata/save/鬼畜王sf.asd
SaveG gamedata/save/鬼畜王sg.asd
SaveH gamedata/save/鬼畜王sh.asd
SaveI gamedata/save/鬼畜王si.asd
SaveJ gamedata/save/鬼畜王sj.asd
